# Generated by Django 3.2 on 2021-04-26 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210426_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='your_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.user'),
        ),
    ]
