# Generated by Django 3.2 on 2021-04-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_your_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='your_name',
            field=models.CharField(max_length=50),
        ),
    ]
